### ISSUE TITLE
Values less then 1 are not blocked, which causes an error

### ISSUE THREAD

**Issue by Fleischers** [Belrestro/js_css_image_slice_slider#1]
`script.js:36 Uncaught TypeError: Cannot read property 'length' of undefined`

**Steps to reproduce:**
1. open index.html
2. set Cells "X" as `-1`
3. set Cells "Y" as `0`
4. Build
5. Voila!

**Comment by Fleischers** [comment]
@Belrestro Was this issue resolved after https://github.com/Belrestro/js_css_image_slice_slider/commit/25355b6f64363ef234f569670756f45633826c7b ?

**Comment by Belrestro** [comment]
Yes sorry for keeping you waiting.
